// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  images_slice: dynamic(() => import("./ImagesSlice")),
  text_slice: dynamic(() => import("./TextSlice")),
  video_slide: dynamic(() => import("./VideoSlide")),
};
